boostorg/boost

status/Jamfile.v2

Adding the sort library to master.

Add sort/test to status/Jamfile.v2

---

libs/libraries.htm

The same change has been merged into develop.

Add new sort library to libraries.html

---

more/getting_started/detail/build-from-source-head.rst

Last try, if it's not right this time, tough.  Sorry!

Update for Oracle 12.4 compiler

---

status/Jamfile.v2

Needed for regression testing on 'develop' branch for VMD

Updated to include VMD tests

---

.gitmodules
status/Jamfile.v2

In order to have VMD added to the next Boost release I am adding VMD tests to 'master'. The tests have been in 'develop' already and I have been watching the results and making any corrections necessary.

Added tests for VMD

---

status/explicit-failures-markup.xml

Related to [this thread](http://article.gmane.org/gmane.comp.lib.boost.devel/264887) on the Boost.Devel mailing list.

[status] Add expected test failures for Hana

---

bootstrap.sh

Make it clear that headers must be generated running a command.

bootstrap improvement regarding headers

---

.gitmodules

Take three.
I also fixed the develop branch of callable_traits to match master, plus the improvements to the test suite from @pdimov .

add callable_traits submodule

---

.gitmodules

Please don't merge this. I'll do it soon-ish, and need to make sure I update functional at the same time.

Extract container_hash from functional

---

doc/Jamfile.v2

Bring in change from develop to allow merging b2 to master.

Remove B2 docs ref.

---

bootstrap.bat

This addition is related to VS2019 (Preview) support.

Add vc142 to recognized toolsets

---

doc/src/minimal.css

CSS files should be UTF-8: https://www.w3.org/International/questions/qa-css-charset

Change encoding to UTF-8 for minimal.css

---

.circleci/config.yml

From this [Dockerfile](https://github.com/boostorg/release-tools/blob/develop/docker/python3/focal/Dockerfile).  Mainly updating software versions.

Newer gems and pip packages in docs build

---

boostcpp.jam

Add support for LoongArch

---

.circleci/config.yml

The same modification as the develop branch last week.  Upgrading the doc build process.

Newer gems in docs build - master branch

---

.circleci/config.yml

Newer build image. Install asciidoctor-diagram, asciidoctor-multipage per @klemens-morgenstern 
cc. @pdimov

CircleCI: update image

---

Jamroot
boostcpp.jam
status/Jamfile.v2

Revert "Revert " Add support for modular build structure.""

---

.github/workflows/commit-bot.yml

This update should be coordinated, let me know in slack when you will merge the PR. At that time I'll comment out the other commitbot.
Before continuing, check permissions in https://github.com/boostorg/boost/settings/actions -> "Workflow permissions" -> "Choose the default permissions granted to the GITHUB_TOKEN".   It ought to be read/write.
I've set the cron schedule to 30 minutes. A problem with a more frequent schedule is sometimes Github Actions get overloaded, and jobs are delayed or overlapping.  
cc. @pdimov

Superproject commitbot in github actions

---

.circleci/autocancel.sh
.circleci/config.yml

Updates the build image, and adds auto-cancel feature. These changes were enabled in the 'develop' branch earlier. Now in the 'master' branch.

CircleCI: autocancel workflows

---

.github/workflows/ci.yml

ubuntu arm runners and windows 2025
