libs/libraries.htm

I assume the qbk documentation that this links into will be built automatically in a master release.  Algorithms seems like the appropriate category for the new sort library.

Add sort to libraries.html

---

tools/Jamfile.v2

The directory tools/regression was removed. So remove the references to it.
Or add the new regression repository as a submodule.

Remove references to removed regression directory

---

.gitignore

Building toolset on Windows platform adds two *.exe files to boost directory and makes repository dirty. Added these two files to ignore list.

Added files 'b2.exe' and 'bjam.exe' to ignore list on windows platform

---

Jamroot

Boost.Log has a boost_log_setup library target that is sometimes needed. Add the target to the top level Jamroot so it is available when using Boost.Build as your build tool.

Add the boost_log_setup target to the top level Jamroot

---

status/explicit-failures-markup.xml

Since CTP 5, lexical_cast_loopback_test passes on MSVC14:
http://www.boost.org/development/tests/develop/developer/output/teeks99-08f-win2012R2-64on64-boost-bin-v2-libs-lexical_cast-test-lexical_cast_loopback_test-test-msvc-14-0-dbg-adrs-mdl-64-lnk-sttc-thrd-mlt.html

Update expected failures for MSVC14

---

status/explicit-failures-markup.xml

It seems that the markup file from master branch is used by the Regression. Therefore it must be updated with the changes made in develop.

Update explicit-failures-markup.xml from develop.

---

status/explicit-failures-markup.xml

This test finally passes with MSVC 14 RTM.

Update ICL failures for MSVC14

---

.travis.yml

Title is self-explanatory. I don't think there's any reason to still use Travis' legacy infrastructure.

[Travis] Run on the container-based infrastructure

---

.gitmodules
libs/libraries.htm
libs/maintainers.txt
status/Jamfile.v2

Specifically:
- Adds Hana's test suite to the regression tests
- Add Hana as the libs/hana submodule
- Add entry for Hana to libs/maintainers.txt and libs/libraries.htm
__NOTE__
This is not ready to be merged yet! I want to see the Travis results so I can adjust some things before this is ready.

Add Hana as a submodule of the master repository

---

.gitmodules
libs/libraries.htm
libs/maintainers.txt
status/Jamfile.v2

This PR is equivalent to https://github.com/boostorg/boost/pull/98, except it targets the master branch instead of the develop branch of the modularized Boost repository.
From my understanding, merging this PR will cause Hana to be included in the next release of Boost. Please do not merge this PR yet; I need to resolve some issues in Hana before it is fully ready to ship with the next version of Boost.

(master branch) Add Hana as a submodule of the master repository

---

.gitmodules
libs/maintainers.txt

Works well on MSVC, GCC, intel and clang compilers.
Known MinGW problem does not seem to be show stopper.

Add stacktrace library to master branch

---

Jamroot

This allows f.ex. `b2 stage --with-system --with-filesystem variant=debug,release link=static,shared runtime-link=static,shared` to work.

Skip link=shared, runtime_link=static instead of aborting the build

---

boostcpp.jam

As a data point, the last MSVC version with a single-threaded runtime is 7.1 (2003). I don't think there's a need to keep building this configuration.

Remove <threading>single from --build-type=complete

---

doc/src/boostbook.css

* `body`'s `font-size` wasn't set. It should though to avoid inconsistencies in font sizes. Fixed.
* [Sphinx](http://www.sphinx-doc.org/en/stable/index.html) uses [Pygments](http://pygments.org/) to highlight the text. Added support for it. The change shouldn't break any existing code.

Make boostbook.css work well with Sphinx

---

Jamroot

`<threadapi>` default value should be deduced from `<target-os>`. The logic is implemented in boostorg/build#251. The actual value of `<threadapi>` (taking into account build request) should be evaluated via `<conditional>` in the top-level project requirements. See also discussion [here](https://github.com/boostorg/thread/commit/e9ce83b3998a0de2a825629531c40aab55b9747c).

Auto-detection of <threadapi> default value

---

status/explicit-failures-markup.xml

The existing call to xmllint returns an error status, the error message is obscured by the output, but it writes to stderr:
explicit-failures-markup.xml:3: validity error : Validation failed: no DTD found !
xsi:noNamespaceSchemaLocation="explicit-failures.xsd">
According to the xmllint man page the `--valid` flag is used for validating using a DTD, and we don't have a DTD. The `--schema` flag is sufficient for validation, so I think the solution is just to remove the `--valid` flag.
I'll accept this myself if no one objects, but I wanted to give people a chance to comment.

Remove --valid flag from xmllint

---

status/explicit-failures.xsd

This is so that this schema can be used to validate module markup (such as https://github.com/boostorg/functional/blob/develop/meta/explicit-failures-markup.xml). An alternative solution would be to have a separate schema file for submodules, espcially if the reporting scripts require these elements to be present.

Make all elements in explicit failures schema optional

---

doc/pdf/build

"/bin/bash" is a Linuxism.  "/usr/bin/env bash" is portable.

Fix bash path in a shebang

---

boostcpp.jam

This requires boostorg/build#209. The corresponding autolink change is boostorg/config#160.

Encode architecture and address model in versioned layout names

---

more/getting_started/detail/common-footnotes.rst
more/getting_started/detail/library-naming.rst
more/getting_started/index.html
more/getting_started/unix-variants.html
more/getting_started/windows.html

I haven't tested this change because I'm not sure how to generate the HTML from the RST.

Update getting_started to reflect the arch-and-model tag

---

status/Jamfile.v2

No longer necessary because of https://github.com/boostorg/wave/commit/4386cce02ef30c1690c7fa4cee5aff05079a267c.

Remove Wave special case from status/Jamfile

---

bootstrap.bat

This allows `bootstrap gcc` to put `using gcc ;` in `project-config.jam` instead of `using msvc ;`.
Supersedes #5.

Record specified toolset in project-config.jam instead of msvc

---

Jamroot

`BOOST_STAGE_LOCATE` is undefined in `boost-install`, so it always uses the target name, `stage`. This means that when `b2 stage` is invoked from, f.ex. `libs/system/build`, a local `libs/system/build/stage` directory is used for staging. This is almost certainly wrong. In addition, `BOOST_STAGE_LOCATE` in `boostcpp` is by default the relative path `stage`, so even if used with `modules.peek`, it works the same way.
I'm not entirely sure that the proposed replacement is correct in all use cases, but it's an improvement. :-)

Fix stage target to not use undefined BOOST_STAGE_LOCATE

---

doc/Jamfile.v2

B2 docs are now generated outside of boostbook. This also fixes a current error on the release archive builds.

Remove B2 docs ref.

---

status/Jamfile.v2

Bring in change from develop to allow merging b2 & predef to master.

Avoid errors when tool submodules do not exist.

---

bootstrap.sh

Better detection of ICU in bootstrap.sh with the help of pkg-config.
Checking for the header under `/usr/include/unicode` is not very robust because on some Linux distros the header is not dirctly in include. E.g. on older Ubuntu 14.04 it is in `/usr/include/x86_64-linux-gnu/unicode`.
Asking pkg-config is a better way to check if the library is installed.

Detect ICU with pkg-config when possible.

---

Jamroot

This commit uses the new visibility feature added in https://github.com/boostorg/build/commit/898ddfa1b6888424eb292942d1014261ac7b6183 and enables hidden visibility by default for Boost libraries.
The discussion that led to this PR is here:
http://boost.2283326.n4.nabble.com/all-Request-for-out-of-the-box-visibility-support-tt4704134.html

Enable hidden visibility by default

---

.travis.yml

Used by Boost.Beast in doc reference generation.

Add SaxonHE to dependencies list

---

status/explicit-failures-markup.xml

Ever since optional references have been rewritten these tests pass in MSVC.

unmarked some optional tests

---

bootstrap.bat

The location of b2 execs changed with release. Need this, or merge of previous equivalent PR, to fix `bootstrap.bat` errors.

"Merge" from develop.

---

bootstrap.sh

This may be the case with, for example, `C:\Program Files\Python37` on MSYS2 on Windows (with `MSYS2_PATH_TYPE=inherit` in the .ini file).

Allow spaces in $PYTHON_ROOT

---

boostcpp.jam

Add s390x as a supported architecture:
* boostcpp.jam
- Add s390x to list of deduced architectures

Add S390x as a supported architecture

---

README.md

Simplest way to address these issues https://lists.boost.org/Archives/boost/2020/04/248731.php
If one aims to clone a repo from GitHub, then README.md is the obvious muscle-memorised place to look at.
-----
By the way, a curated `CONTRIBUTING.md` could replace the mess on the Wiki as a single source of truth.

Add how-to clone the superproject to README.md

---

Jamroot

This makes it possible to `import config` instead of using a relative path requiring package managers to patch the files.

Make config module availabe to subprojects

---

bootstrap.sh

Many CI setups set CXX without user consent and without the ability to unset it. This causes the b2 build to fail as setting CXX for it is and intentional user choice that needs special care. This avoids the issue by clearing out CXX when invoking build.sh.

Prevent CXX leaking into build.sh script.

---

bootstrap.sh

Looks like CXXFLAGS is also magically set in some CI setups to incompatible values to the toolset b2 uses for bootstrap. This clears it to avoid the confusion.

Also prevent leaking CXXFLAGS from CI setups.

---

bootstrap.sh

I've now gotten a few requests to restore the ability to specify the toolset that b2 is built with through the Boost root bootstrap.sh script. This change brings that aspect back. But it also clarifies what that option does and the ensuing results in the output.

Bring back with-toolset applying to b2 build.

---

bootstrap.bat

Pass down user's toolset override to the `b2`-building script. This was (most likely erroneously) removed in 26232c8 along with the output redirection.
If user provided toolset of "borland" for bootstrapping, prepare `project-config.jam` for the modern `embarcadero` toolset.

Allow bootstrapping with "borland" (Embarcadero)

---

.circleci/config.yml

Boost archives are not being published to jfrog because of the recent Let's Encrypt problem.  
Rebuilding the docker images solves the issue.  
Dockerfiles: https://github.com/boostorg/release-tools/pull/18/files
Still python2, instead of python3.
cppalliance/boost_superproject_build:build-deps-3 based on Ubuntu 16.04
cppalliance/boost_superproject_build:build-deps-4 based on Ubuntu 18.04
Organizationally, it would make sense to host the docker images at boostorg/ instead of cppalliance/ .    You are welcome to make that change: Rebuild with "docker build".   Upload to boostorg/ .

Rebuilt circleci docker image

---

.circleci/config.yml

Changes the circleci config, to use the python3 branch of release-tools.

Update release-tools to python3

---

boostcpp.jam

In fact mips1 is now used for all mips revisions.

Rename mips1 to mips

---

.circleci/config.yml

The python3 update to release-tools has run for a couple of releases. Merging those changes into the master and develop branches.  Pointing CircleCI to use the develop branch.

circleci: change branch of release-tools

---

boostcpp.jam

Android studio could automatically pack shared libraries into final apk. But if we link to `libboost_system.so`, which is a soft link to `libboost_system.so.1.68.0`, only the former will be packed.

do not add version suffix for android

---

.circleci/config.yml

Add `rclone` and `aws cli` packages to the image, when building a release.

CircleCI: update image

---

.circleci/config.yml

Updates CircleCI Docker image to `cppalliance/boost_superproject_build:20.04-v3`, which includes nodejs.

CircleCI Docker image supports antora builds

---

boostcpp.jam

This should finally fix bfgroup/b2#368.
Background. After my b2 PR (bfgroup/b2#375) was merged, the build system is properly creating two alternatives for checked libraries (e.g. `/openssl//ssl`): before the deduced properties are added, and after that. What this **does not** result in, though, is build system actually compiling and linking corresponding files twice. This is because `deduced-X` are _hidden_ features, and they do not affect the target path. As a result `foo.o` with `address-model=32` , and `foo.o` with `address-model=32 deduced-architecture=x86` result in the same file (e.g. `gcc-13/debug/address-model-32/threading-multi/visibility-hidden/foo.o`, notice the lack of `architecture`).
After some thinking, I decided that this is a flaw in how deduced platform features are …

fix deduction not properly working

---

Jamroot
boostcpp.jam

This changes separate deduction of `address-model` and `architecture` with a single `x-deduced-platform` (the corresponding rule is `platform`. The purpose of this is to shorten the target path, while keeping it unique for different configurations.
The logic of the conditional rule is this:
1. If there's already `x-deduced-platform` in the property set, then return that (this is needed for repeated evaluation of conditionals).
2. If eihter `address-model` or `architecture` could not be deduced, return nothing.
3. Get  `address-model` and `architecture` properties from the property set, assign deduced values to any if it is empty.
4. Construct the corresponding value of `x-deduced-platform`. If there's no corresponfing value (e.g. user requested an architecture we don't support for …

unified implict feature for platform deduction

---

boostcpp.jam

The old names were referenced in Boost libraries and it's easier to return to old names than fixing every reference.

revert names of conditional features for deduction

---

.circleci/autocancel.sh
.circleci/config.yml

Note: create an API token before proceeding.
To prevent a problem with multiple commits occurring at nearly the same time and overwriting snapshots, there are two solutions:  
1. Force sequential builds. However, a difficulty is that each build takes 45 minutes, so when 10 commits happen in sequence the final snapshot won't be ready for 7 hours.
or
2. Cancel previous in-progress builds. Only the newest commit is relevant when building a snapshot. This generally seems preferable since it's faster. A small disadvantage is that if one commit out of ten caused an error, it won't be immediately obvious which commit caused the error.  Not often an issue.
This PR cancels in-progress builds. As an enhancement, it checks the time, and only cancels other jobs from within the last 10 minutes. Any …

CircleCI: autocancel workflows

---

Jamroot

Accidentally added a dependency on the generated boost header tree for all targets. The boost headers generation only works if it's an implicit-dependency. As otherwise dependents think they are never up to date.

Fix repeated builds of targets.

---

.github/workflows/commit-bot.yml

Note: Before merging, please add a gha secret "CI_PAT" .
- In a personal github account, create a token that has permission to push to this superproject.  
- At https://github.com/boostorg/boost/settings/secrets/actions  create a gha secret "CI_PAT", and enter the token.  
From https://github.com/orgs/community/discussions/25702  "If an action pushes code using the repository’s GITHUB_TOKEN, a new workflow will not run"  
Updates in this PR:
- Modify the git token to be `secrets.CI_PAT`
- Only run on a cron schedule, not from pushes
- Fix the git submodule url variable. During testing it had been set to a full url such as `https://github.com/boostorg/math.git`. In production the format is `../math.git`.  Convert to a url.  
cc. @glenfe @pdimov

Superproject commitbot fixes

---

boostcpp.jam

In b2 `$(a) in A B C` is true when `$(a)` is empty (empty set is a subset of any set). So, the tag will produce a result for untyped targets, which is clearly not intended.
This currently does not happen anyway, because b2 doesn't run `<tag>`s for untyped targets, but I intend to change that, so that users could do `make a : : @make-rule : <tag>@tag-rule ;`

guard tag against empty type

---

.github/workflows/commit-bot.yml

Nearly all developers who fork the superproject would not need their own version of commit-bot running.   
Usually it doesn't work. The token is missing. Or, if it is configured to run successfully, that will cause divergent commits in the fork.  
As shown, what this pull request does is have the commit-bot check it's in "boostorg/boost".  @pdimov please merge this, whenever convenient. It should be observed over the subsequent few hours to be sure the bot continues to run.

Github Actions: commitbot runs conditionally on boostorg/boost repo

---

.circleci/config.yml

Reverts boostorg/boost#941
Because of
```
*** buffer overflow detected ***: terminated
```

Revert "CircleCI: update image"

---

doc/html/boostbook.html
tools/index.html

The documentation is built at tools/boostbook/doc/html, and tools/boostbook/index.html contains a universal redirect to the actual location of the docs entry point.
This also resolves the circular redirect in doc/html/boostbook.html.
Refs https://github.com/boostorg/boost/issues/937.

Update links to BoostBook documentation

---

.circleci/config.yml

The newer image is already in place on the `develop` branch.
cc. @pdimov

CircleCI: 24.04 image

---

Jamroot

This fixes the usage in CLI of features defined in subprojects. I've mentioned the problem several times on Slack and also described it in a [Boost Users' ML post](https://lists.boost.org/Archives/boost/2024/10/258033.php).

fix using subproject features

---

.github/workflows/ci.yml

GitHub/Microsoft no longer provides ubuntu-20.04 testing.

Remove Ubuntu 20.04

---

tools/Jamfile.v2

Modular building delegates, and normalizes, the building of tools inside the tools themselves. This makes it possible to avoid a bunch of code at this level. This change also adds default building for all current tools.

Simplify for modular building.

---

.github/workflows/ci.yml

Fixes issue : https://github.com/boostorg/boost/issues/1070
Draft PR for the review.
.gitmodules changes were done to build in my fork. They will be discarded in the due course.

Add Windows on ARM64 GitHub Actions CI support

---

CMakeLists.txt

Most libraries are C++11 and require CMake 3.8 for the CMake feature or depend on libraries that do.
Drop support for earlier CMake versions in the super project to reduce the number of versions to verify.
This comes from my experiments in the tools/cmake repo testing a range of CMake versions.
The list of libraries not supporting CMake < 3.8 keeps on growing so I'd say it doesn't make sense anymore to support that going forward. I'm currently at over 60 libraries that require CMake 3.8, there are others (around a dozen or so) that require even higher versions.
(Incomplete) list of libraries incompatible with CMake 3.7:
> outcome;asio;atomic;beast;bind;bloom;callable_traits;charconv;chrono;compat;container_hash;contract;crc;date_time;endian;fiber;filesystem;format;function;geometry;gil;gra …

Update required CMake version to 3.8
